batch_size: 16
num_classes: 2
num_clones: 4
max_epochs: 600
learning_rate_decay_type: 'exponential'
learning_rate_decay_factor: 0.9
num_epochs_per_decay: 2
optimizer: 'rmsprop'
learning_rate: 0.00005
end_learning_rate: 0.00001
r_mean: 122.518703
g_mean: 109.342718
b_mean: 102.872242
num_samples: 100000
output_size: 128
origin_height: 700
origin_width: 700
